domain: yourdomain.com
title: 你的名字
title_ext: slogan

contacts:
  - icon: "fa fa-envelope"
    url: "hi@example.com"
    text: hi@example.com
  - icon: "fa fa-qq"
    text: 10000
  # - icon: "fa fa-wechat"
  #   text: wechat-username

domains:
  - domain: 5.nu
    description: "@Give me five✋"
  - domain: BigToysCompany.com
    description: "@大玩具"
